#!/usr/bin/env python3

import numpy as np
import py_functions as pf
import matplotlib.pyplot as plt
import os
import sys
import subprocess

arguments = []
for arg in sys.argv[1:]:
    arguments.append(arg)

U_list = np.linspace(0,3,10)
GAMMA_list = np.linspace(0,1,10)
T_list = np.array([0.0001,0.001,0.01,0.1,1.0])
#T_list = arguments

os.system('mkdir graphs_and_data/sweep_fixed_t')
for t in T_list:
    os.system( 'mkdir graphs_and_data/sweep_fixed_t/t-{:6.4f}'.format(float(t)) )
    for gamma in GAMMA_list:
        for u in U_list:

            pf.write_param( u , gamma , t )
            subprocess.call( './1_fullrun && ./p_mag graphs_and_data/sweep_fixed_t/t-{:6.4f}/u-{:6.4f}_g-{:6.4f}.png'.format(float(t), \
                    float(u),float(gamma)) , shell=True )
            

        
