#!/bin/bash


./99_f_extract e 0 1 1 >e-q0s1_table1.dat
./99_f_extract e 0 1 2 >>e-q0s1_table1.dat
./99_f_extract e 0 1 3 >>e-q0s1_table1.dat

./99_f_extract e 0 3 1 >e-q0s3_table1.dat


./99_f_extract e 1 2 1 >e-q1s2_table1.dat
./99_f_extract e 1 2 2 >>e-q1s2_table1.dat


./99_f_extract e 2 1 1 >e-q2s1_table1.dat
